preset: conventionalcommits
branches:
  - name: rc
    prerelease: "rc"
  - name: release
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: revert
          release: patch
        - type: perf
          release: patch

  # This creates fancy release notes in our Github release
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

  ### Block(customReleasePlugins)

  # Build the orb
  - - "@semantic-release/exec"
    - prepareCmd: make
  - - "@outreach/semantic-release-circleci-orb"
    - orbName: "getoutreach/shared"
      orbPath: "orb.yml"
  ### EndBlock(customReleasePlugins)
