preset: conventionalcommits
branches:
  - name: main
    prerelease: "rc"
  - name: release
plugins:
  - - "@semantic-release/commit-analyzer"
    - releaseRules:
        - type: revert
          release: patch
        - type: perf
          release: patch

  # This creates fancy release notes in our Github release
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: make build-orb
  - - "@getoutreach/semantic-release-circleci-orb"
    - orbName: getoutreach/shared
      orbPath: orb.yml

  ## <<Stencil::Block(customReleasePlugins)>>

  ## <</Stencil::Block>>
