[tools]
"github:getoutreach/devenv" = "1.64.7"
"github:getoutreach/kubecfg" = "0.28.1"
kubectl = "1.34.7"
# The following is copied from mise.devbase.toml, sync versions from there
## ECR
aws-cli = "2.34.31"
## GitHub authn
"github:getoutreach/ci" = "1.6.14"
github-cli = "2.83.2"
## Sync with templates/scripts/devbase.sh.tpl
gojq = "0.12.18"
## E2E auth (devenv provision uses vault)
vault = "2.0.0"
gotestsum = "1.13.0"
# Work around GitHub token rate limits
wait-for-gh-rate-limit = "1.1.1"
