#!/usr/bin/env bash
#MISE description="Formats Go source files."

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
SHELL_DIR="$DIR/../../../shell"

exec "$SHELL_DIR/run-formatter.sh" "$SHELL_DIR/linters/go.sh"
