# Please re-run stencil after any changes to this file.
version: 2.1
orbs:
  shared: getoutreach/shared@1.60.0

# Extra contexts to expose to all jobs below
contexts: &context
  ### Start contexts inserted by other modules
  ### End contexts inserted by other modules
  ###Block(extraContexts)
  - docker-registry
  - npm-credentials
  - ghaccesstoken
  - package-cloud-credentials
  ###EndBlock(extraContexts)

jobs:
  {}
  ###Block(circleJobs)

  ###EndBlock(circleJobs)

  ### Start jobs inserted by other modules
  ### End jobs inserted by other modules

workflows:
  version: 2
  ###Block(circleWorkflows)

  ###EndBlock(circleWorkflows)

  ### Start workflows inserted by other modules
  ### End workflows inserted by other modules

  release:
    jobs:
      ###Block(circleWorkflowJobs)

      ###EndBlock(circleWorkflowJobs)
      - shared/release: &release
          dryrun: false
          context: *contexts
          ###Block(circleReleaseExtra)

          ###EndBlock(circleReleaseExtra)
          requires:
            ###Block(circleReleaseRequires)

            ###EndBlock(circleReleaseRequires)
            - shared/test
          filters:
            branches:
              only:
                - master
                - main
                - release
      # Dryrun release for PRs
      - shared/release:
          <<: *release
          dryrun: true
          filters:
            branches:
              ignore:
                - master
                - main
                - release
      - shared/test:
          context: *contexts
          app_name: devbase

      - shared/publish_docs:
          context: *contexts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
      - shared/finalize-coverage:
          context: *contexts
          requires:
            - shared/test
