[package]
name = "gql_lint_cli"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "gql-lint"
path = "src/main.rs"

[[bench]]
harness = false
name = "lint"

[dependencies]
anyhow = { workspace = true }
apollo-compiler = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
gix = { version = "0.87", default-features = false, features = ["revision", "sha1"] }
globset = { workspace = true }
gql_lint_core = { workspace = true }
gql_lint_rules = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[lints]
workspace = true
