description: Sets up CI with environment configuration
parameters:
  machine:
    type: boolean
    default: false
  setup_remote_docker:
    type: boolean
    default: false
  checkout:
    type: boolean
    default: true
steps:
  - when:
      condition: << parameters.setup_remote_docker >>
      steps:
        - use_docker
  - when:
      condition: << parameters.checkout >>
      steps:
        - checkout
  # Adds a github org scoped SSH key to the project added by Wheatley
  - add_ssh_keys
  # When in machine mode we need to install some dependencies
  - when:
      condition: << parameters.machine >>
      steps:
        - run:
            name: Install Dependencies
            command: |-
              # remove the existing yq, if it already exists
              sudo apt-get autoremove yq || false

              # yq
              pip3 install yq

              # Vault
              curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
              sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
              sudo apt-get update
              sudo apt-get install -y vault
  - run:
      name: Setup CI Environment
      command: ./scripts/shell-wrapper.sh circleci/setup.sh
