description: Sets up CI with environment configuration
parameters:
  machine:
    type: boolean
    default: false
  setup_remote_docker:
    type: boolean
    default: false
  checkout:
    type: boolean
    default: true
  setup_devenv:
    description: Setup a fully provisioned devenv. Do not use for E2E, use setup_devenv with e2e instead.
    type: boolean
    default: false
steps:
  - when:
      condition: << parameters.setup_remote_docker >>
      steps:
        - use_docker
  # Adds a github org scoped SSH key to the project added by Wheatley
  - add_ssh_keys
  - when:
      condition: << parameters.checkout >>
      steps:
        - checkout
        - run:
            name: Checkout Submodules
            command: git submodule sync && git submodule update --init
  # When in machine mode we need to install some dependencies
  - when:
      condition: << parameters.machine >>
      steps:
        - run:
            name: Install Dependencies
            command: ./scripts/shell-wrapper.sh circleci/machine.sh
  - when:
      condition: << parameters.machine >>
      steps:
        - run:
            name: Setup CACHE_VERSION
            command: |-
              # Setup a cache-version.txt file that can be used to invalidate cache via env vars in CircleCI
              echo "$CACHE_VERSION" > cache-version.txt
        - restore_cache:
            keys:
              - v1-asdf-cache-{{ checksum "cache-version.txt" }}
  - run:
      name: Setup CI Environment
      command: ./scripts/shell-wrapper.sh circleci/setup.sh
  - when:
      condition: << parameters.setup_devenv >>
      steps:
        - setup_devenv
  - when:
      condition: << parameters.machine >>
      steps:
        - save_cache:
            key: v1-asdf-cache-{{ checksum "cache-version.txt" }}
            paths:
              - "~/.asdf"
