#!/usr/bin/env bash
#MISE description="Run Stencil on the current repo without updating any module versions."
#MISE tools={"github:getoutreach/stencil" = "latest"}
#MISE depends=["devbase:sync"]
#MISE depends_post=["stencil:post"]

exec stencil --skip-update --frozen-lockfile
