#!/usr/bin/env bash
#MISE description="Run Stencil on the current repo without updating any module versions."
#MISE depends=["devbase:sync"]
#MISE depends_post=["stencil:post"]

set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
LIB_DIR="$DIR/../../../shell/lib"

# shellcheck source=../../../shell/lib/mise/stub.sh
source "$LIB_DIR/mise/stub.sh"

mise_exec_tool_with_bin github:getoutreach/stencil stencil --skip-update --frozen-lockfile
