#!/usr/bin/env bash
#MISE description="Run Stencil on the current repo and update any module versions if available."
#MISE tools={"ubi:getoutreach/stencil" = "latest"}
#MISE depends_post=["stencil:post"]

exec stencil --skip-update
